language: node_js
node_js:
- 'node'
sudo: false
notifications:
  email: false
  slack:
    secure: Njn9VjYMUJcb8jfvusetb13uC0rcQ1NN6KumKxc6/jBCRoQ7uhQbqhcemZDK/7s/jRUGYTkb72u5QJxgVHcYDMchO9aOCVI3xs8veQ6j6shOCJbSIHGby1nkuwDPNzyyYh5mjJVDiWbiIBOzOaMko0QT//Ce1IitBBkyTEtQPcg=
before_install:
  - npm config set spin false
  - npm install -g npm
after_success:
  - bash <(curl -s https://codecov.io/bash)
