language: node_js
node_js:
- '6'
cache:
  npm: true
  bower: true
sudo: false
services:
- docker
dist: trusty
addons:
  chrome: stable
before_install:
  google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
jobs:
  include:
  - stage: deploy
    script:
    - npm run build
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      quay.io
    - bash docker.sh
  - stage: test
    script:
    - npm run prot
notifications:
  slack:
    secure: Njn9VjYMUJcb8jfvusetb13uC0rcQ1NN6KumKxc6/jBCRoQ7uhQbqhcemZDK/7s/jRUGYTkb72u5QJxgVHcYDMchO9aOCVI3xs8veQ6j6shOCJbSIHGby1nkuwDPNzyyYh5mjJVDiWbiIBOzOaMko0QT//Ce1IitBBkyTEtQPcg=
env:
  global:
  - secure: ljA7iWFK+DWDcgrXYUcDdczgVa79NDcZ8fq0y2+oMZicVVrswcxndIoLI15U6M1XapKndLaAuDKZAaFlndXUpp7/eNw+EgT1JvfSDAn58bQ8z14Zj31za9k+bsqbNS+k+Ft5VFQLCvBfeQgZnC4fzE2BVShQ3At+2/S+a7nn2HVwV7qfCLR+v/u1EFXvLifQZVbNYmp/6pCx1LLmckfjaldxAPHaCwE7oc+4+bmwK25hKD9w7GCSawU+f0wAgBDd3pNYxWn5iDK3Uh4dQpDGi/2aXRNTK7gUapgWDiG+ECyNmQ04dOUMGUqTAKljB0wUu8Xp/vxwdo7LQ9n4AnFQ5ucw1bBOLjivNuNCTe3WiQLTgUvt+p/zvsqBMoo6J9Fi6KvTH1oOajkfdBU/cNjxRQH/FO815B3nJLt1HzjeM+zCJ2XKBt6CGeyfmybtUejxkhEAoh/a6RH9S7sKbXlxAE9MHim2RV74mKUtLD9YZauYdBPtQGf2DYTtaj4QErPcaq8NJbNlyhbYDLRDsXOoyBeyKEprySVSLy1bxiWgBw+ZeDHit31CuVst0T3sNV+/8qCa/p1Cxvz+/V0kuUxIwkgQNDi0nFZ2EHglZ5u0Mx/zhzGGxB+UCmqf69Az0ghjxO9TCla7n9rL93ib4TcYK4a9rLDckD1F15rswNJcIOI=
  - secure: oKdwuM1KSe7yel+yoZYJXXoRvxc/gbp/eyyTt8hnn5/Lz1tx7UGg0PAb9eXJoLgW3KOYSBpxTFKZgPoUFLuQiGULBy1DUK6yICd/lFVxYSXrPAsSs1mg4UKxqXQP1mYUGOX4UvNSIbX97xiXf4IOldxUqh7G0kMWbiZLObag5lmX3tfw/sgB2xvohugDsQLuSqIi658/BZ3qbc156TSLp5vjqQ0uEMv29fvybudbpAjaf4VJ1KuoFSJbcu673g1i33CYZfyZs4zNW448rnnS+HV4kWf9LW1aoMMWPwAL5FIAWilQ6cXp0Ze1e5fvFJIQcHO6LRvvMRJLlCHQimfEWCm0ObPppR4YQyi3/EY/Ski4M7fIw4+9unT+cvbLLHb08dLYtEDypqPHqdrQ2uaxHokLFtjdXtMsOgoqg7RzmL1Z4PrOVkyoa2/0hntzKnCApKp7hcu2w3KrXdgbju5b+bqz+UboCwxTxzOwd6vu7d+E8S1QwhFlpQRdYYn/KDvCPFmvIV2BqI2yOLNCtFQ4ejh140rJC4VRlra+rOFE32YP/3mi2WT67W6oChCS1ZSzFRNsZfiRgu/BTQd6Qqig9hHkFWOYF6pSizwf4PWNYRMkO/TenHKHzIeIlyDyNxQ3D5lXH+tIVXugZ7TT9Epa/EMgHgeO1v/Fi6Sl9ToRtYM=
  - secure: EuCn6r8/OV2GR4UnGmOiEfHFNvh1nH/FcaGcXstv5VHjb7GsfMuH1PpIimpKNQv8+wSNIb8agLbB7aK/49edPSG3L2Iw/bHsk7G5fFW4oh+7SS8TuhIk/RbVtaHRD1MN7yvsUFyCBuv/p8++hCUnUq/1f8e2V2Uo0qg1jwLX4rqWhYrT3ax2gvQS5PD+5MlkE7DpSwfaFbUAqe4x9j+UritIW/nuHZ6b5ZK1a1LHDLGwHoyJIep2Z/4KN3hTdFxTyOeeUd50T4k4Wh7R5z43CUVZVuOQ4sY+PwrlxQGUB01up2Z1vB1jgCoisiOjT32aZS4k3rbp7qZwWNudm8sEyUTayzuDFhZmGuxuMrly342ury8LloQQHA6EEmDi2leF0yT8PwPlYo+W30yK/rTjLRKUrNzW3HvU5fWPIVhkCXW9CFdCF5X9kTO0KydyS2hOGt6BzY5GMpV5EtU8q2E0XEa1Ez3cGo2xJvrm8swRY5gWXHIrLIVY5cmrq4Tvjzkqdy/UcM0m2b1lbjhCw5R201oHLeAbdAlsowwGhsc/K8fnaQbP/txmgw6/1TePncnsBnuRlC+VsbRpQtvKVqfP4g+E425QxtKGs6rh7M76onm8djWJ5k8qhVNp/PVW1s1xD+VDcbonQ2DOCem8qjtsvLNzZfYG1oHmNLIARWO+/A4=
  - secure: PtsazszIioqyU1F509Fl0aKo0l+RFLaPJwuDMxi2Biy6QqwTO3ez6ogR3WKn6v9Aot66djKvEmaP0MYO8q37gZcsEU3v+QY6i9WjDopdhcUSJL/d5dGlOcXCUZdtHB9tUozq6y23C2mFdhnDCCJ56qOPpZgGml8jnkAesIn076YBRmfOeDiDFkWUqFnKpyOubNLnwfZ9vDsrkrLVcWGwvNO5ktXLYvF7g7QXoUTzmnzMR7F/qXNrCLL5BZmvC/WbOwThC6EGrJ2gqvBaopS2rhEOmjdyzpOeXfMink2h8AAHVmfltJXCQehhrhXQp13iLx9jK8eooGMkvT9TJwzDaMTFWjhMqVKwDsbt0ULWbKDEg0VO9mYoEj5w2d1kCmxW4PKEeUn3J0d9dvcCkYa97E2jBoWXIt7kjFL52WPktT3fME7T01mRIebVqOVXfnnJHcSqP8I05tr645+GjVTdQ3E+Szxj+70Wh118WvjkQiK/75aSRgfaJby3piTThWvOZ74JV0orB9pbXezYJY+T59Mq8k0m+bZ6nDKs3aA/T4m8O5IhJ8TSSRGc6HCG6gX/aRC6REAs8ZXUBw9IeFVSYkYPdQJhTuiBnm2uabQTKv9HUlUWq2yKtsVsFRewK9pIJwX101nktCHj9C05tCwbTrCCwO0LY4vrGOQnmYs8als=
