codecov:
  token: 5656c4b1-41c8-4634-8c99-bf3dfa407fc3
  branch: develop
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
